# Generated by Django 5.0.2 on 2024-06-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("link", models.CharField(max_length=1000, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "db_table": "Providers",
            },
        ),
        migrations.RemoveField(
            model_name="application",
            name="title",
        ),
        migrations.AddField(
            model_name="application",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок поставки"),
        ),
        migrations.AddField(
            model_name="position",
            name="is_done",
            field=models.BooleanField(default=1, verbose_name="Закуплена"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="min_quantity",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Минимальное количество"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="purchase_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.purchase_topic",
                verbose_name="Тема закупки",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="units",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.unit",
                verbose_name="Единица измерения",
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=1000, verbose_name="Ссылка")),
                (
                    "appl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.application",
                        verbose_name="Для заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка",
                "verbose_name_plural": "Ссылки",
                "db_table": "Links",
            },
        ),
        migrations.AddField(
            model_name="position",
            name="link",
            field=models.ManyToManyField(
                blank=True, to="mrp.link", verbose_name="Сслыки"
            ),
        ),
        migrations.CreateModel(
            name="PositionInApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(verbose_name="Количество")),
                ("link", models.CharField(max_length=1000, verbose_name="Ссылка")),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.position",
                        verbose_name="Позиция",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="application",
            name="positions",
            field=models.ManyToManyField(
                blank=True, to="mrp.positioninapplication", verbose_name="Позиции"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.provider",
                verbose_name="Поставщик",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TraceLogUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_units", models.FloatField()),
                ("action", models.CharField(max_length=300, verbose_name="Действие")),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.position",
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
                "db_table": "TraceLogUnits",
            },
        ),
    ]
