# Generated by Django 5.0.2 on 2024-06-03 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="provider",
            field=models.CharField(default=1, max_length=500, verbose_name="Поставщик"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="link",
            field=models.CharField(default=1, max_length=500, verbose_name="Ссылка"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="positions",
            field=models.ManyToManyField(
                blank=True, to="mrp.position", verbose_name="Позиции"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="purchase_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.purchase_topic",
                verbose_name="Тема закупки",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="units",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.unit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
