# Generated by Django 5.0.2 on 2024-06-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0002_application_provider_position_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="link",
            field=models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
        ),
        migrations.CreateModel(
            name="TraceLogUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_units", models.FloatField()),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.position",
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
                "db_table": "TraceLogUnits",
            },
        ),
    ]
