# Generated by Django 5.0.2 on 2024-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0002_provider_remove_application_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="payment_form",
            field=models.CharField(
                choices=[
                    ("option1", "Опция 1"),
                    ("option2", "Опция 2"),
                    ("option3", "Опция 3"),
                ],
                default="option1",
                max_length=100,
                verbose_name="Оплата",
            ),
            preserve_default=False,
        ),
    ]
