# Generated by Django 5.0.2 on 2024-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0003_alter_position_link_tracelogunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracelogunit",
            name="action",
            field=models.CharField(
                default="взял", max_length=300, verbose_name="Действие"
            ),
            preserve_default=False,
        ),
    ]
