# Generated by Django 5.0.2 on 2024-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0003_application_payment_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="payment_form",
            field=models.CharField(
                choices=[("Постоплата", "Постоплата"), ("30/70", "30/70")],
                max_length=100,
                verbose_name="Оплата",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(blank=True, max_length=300, verbose_name="Название"),
        ),
    ]
