# Generated by Django 5.0.2 on 2024-06-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0004_alter_application_payment_form_alter_provider_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="positioninapplication",
            name="units",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
    ]
