# Generated by Django 5.0.2 on 2024-06-04 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0004_tracelogunit_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deadline",
            field=models.DateField(
                blank=True, default=datetime.date.today, verbose_name="Срок поставки"
            ),
        ),
    ]
