# Generated by Django 5.0.2 on 2024-06-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0006_alter_application_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="count_pos",
            field=models.FloatField(default="1", verbose_name="Количество"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="units",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="mrp.unit",
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
    ]
