# Generated by Django 5.0.2 on 2024-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0006_applicationtechnicalspecification"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtechnicalspecification",
            name="file_name",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Имя файла"
            ),
        ),
    ]
