# Generated by Django 5.0.2 on 2024-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0007_applicationtechnicalspecification_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtechnicalspecification",
            name="file_name",
            field=models.CharField(default=1, max_length=100, verbose_name="Имя файла"),
            preserve_default=False,
        ),
    ]
