# Generated by Django 5.0.2 on 2024-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0007_application_count_pos_application_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="link",
            field=models.CharField(default=1, max_length=500, verbose_name="Ссылка"),
            preserve_default=False,
        ),
    ]
