# Generated by Django 5.0.2 on 2024-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0008_alter_applicationtechnicalspecification_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationtechnicalspecification",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя файла"
            ),
        ),
    ]
