# Generated by Django 5.0.2 on 2024-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0008_application_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок поставки"),
        ),
    ]
