# Generated by Django 5.0.2 on 2024-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0009_alter_applicationtechnicalspecification_file_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
                "db_table": "Equipments",
            },
        ),
        migrations.AlterModelOptions(
            name="positioninapplication",
            options={
                "verbose_name": "Позиция в заявке",
                "verbose_name_plural": "Позиции в заявке",
            },
        ),
        migrations.AlterModelTable(
            name="positioninapplication",
            table="PositionsInApplication",
        ),
    ]
