# Generated by Django 5.0.2 on 2024-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0009_alter_application_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="min_quantity",
            field=models.FloatField(default=10, verbose_name="Количество"),
            preserve_default=False,
        ),
    ]
