# Generated by Django 5.0.2 on 2024-06-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0010_equipment_alter_positioninapplication_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Количество"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EquipmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_form",
                    models.CharField(
                        choices=[("Постоплата", "Постоплата"), ("30/70", "30/70")],
                        max_length=100,
                        verbose_name="Оплата",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок поставки"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True, to="mrp.equipment", verbose_name="Оборудование"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.provider",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "purchase_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.purchase_topic",
                        verbose_name="Тема закупки",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mrp.status",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на оборудование",
                "verbose_name_plural": "Заявки на оборудование",
                "db_table": "EquipmentApplications",
            },
        ),
    ]
