# Generated by Django 5.0.2 on 2024-09-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0012_equipment_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200, verbose_name="Путь")),
                ("is_used", models.BooleanField(verbose_name="использован")),
                (
                    "purchase_type",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="тип заявки"
                    ),
                ),
                (
                    "purchase_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="номер заявки"
                    ),
                ),
            ],
            options={
                "verbose_name": "путь",
                "verbose_name_plural": "пути",
                "db_table": "paths",
            },
        ),
    ]
