# Generated by Django 5.0.2 on 2024-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0015_path_is_shown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase_topic",
            name="stage",
            field=models.IntegerField(blank=True, null=True, verbose_name="Этап"),
        ),
    ]
