# Generated by Django 5.0.2 on 2024-02-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_add",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("deadline", models.DateField(blank=True, verbose_name="Дата сдачи")),
                ("done", models.BooleanField(verbose_name="Выполнено")),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "date_add",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("deadline", models.DateField(blank=True, verbose_name="Дата сдачи")),
                ("done", models.BooleanField(verbose_name="Выполнено")),
                (
                    "main_task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm.task"
                    ),
                ),
                ("executors_id", models.ManyToManyField(to="crm.user")),
            ],
            options={
                "verbose_name": "Подзадача",
                "verbose_name_plural": "Подзадачи",
                "db_table": "subtasks",
            },
        ),
    ]
