# Generated by Django 5.0.2 on 2024-02-12 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "date_add",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("deadline", models.DateField(blank=True, verbose_name="Дата сдачи")),
                ("is_done", models.BooleanField(verbose_name="Выполнено")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "db_table": "projects",
            },
        ),
        migrations.RenameField(
            model_name="task",
            old_name="done",
            new_name="is_done",
        ),
        migrations.RemoveField(
            model_name="subtask",
            name="executors_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="img",
        ),
        migrations.AddField(
            model_name="task",
            name="executors_id",
            field=models.ManyToManyField(to="crm.user"),
        ),
        migrations.AddField(
            model_name="task",
            name="main_project_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.project",
            ),
            preserve_default=False,
        ),
    ]
