# Generated by Django 5.0.2 on 2024-02-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_experiment_variation_alter_subtask_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtask",
            name="description",
        ),
    ]
