# Generated by Django 5.0.2 on 2024-02-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_subtask_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtask",
            old_name="done",
            new_name="is_done",
        ),
    ]
