# Generated by Django 5.0.2 on 2024-02-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_experiment_main_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_add",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="date_add",
            field=models.DateField(auto_now=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_add",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comment_files/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "main_task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
                "db_table": "comments",
            },
        ),
    ]
