# Generated by Django 5.0.2 on 2024-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_rename_user_empl_remove_task_executors_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="executors_id",
            field=models.ManyToManyField(blank=True, to="crm.empl"),
        ),
    ]
