# Generated by Django 5.0.2 on 2024-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_task_executors_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
