# Generated by Django 5.0.2 on 2024-09-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_path"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Path",
        ),
    ]
